using System;
using Rewired.Internal.Localization;

namespace Rewired.Interfaces
{
	// Token: 0x020001EB RID: 491
	[CustomObfuscation(rename = false)]
	[CustomClassObfuscation(renamePrivateMembers = false, renamePubIntMembers = false)]
	internal interface IControllerElementIdentifierCommon_Internal
	{
		// Token: 0x17000603 RID: 1539
		// (get) Token: 0x060018D6 RID: 6358
		int id { get; }

		// Token: 0x17000604 RID: 1540
		// (get) Token: 0x060018D7 RID: 6359
		string name { get; }

		// Token: 0x17000605 RID: 1541
		// (get) Token: 0x060018D8 RID: 6360
		string positiveName { get; }

		// Token: 0x17000606 RID: 1542
		// (get) Token: 0x060018D9 RID: 6361
		string negativeName { get; }

		// Token: 0x17000607 RID: 1543
		// (get) Token: 0x060018DA RID: 6362
		string nonLocalizedName { get; }

		// Token: 0x17000608 RID: 1544
		// (get) Token: 0x060018DB RID: 6363
		string nonLocalizedPositiveName { get; }

		// Token: 0x17000609 RID: 1545
		// (get) Token: 0x060018DC RID: 6364
		string nonLocalizedNegativeName { get; }

		// Token: 0x060018DD RID: 6365
		string GetSpecialElementNonLocalizedName(int index);

		// Token: 0x1700060A RID: 1546
		// (get) Token: 0x060018DE RID: 6366
		string key { get; }

		// Token: 0x1700060B RID: 1547
		// (get) Token: 0x060018DF RID: 6367
		string positiveKey { get; }

		// Token: 0x1700060C RID: 1548
		// (get) Token: 0x060018E0 RID: 6368
		string negativeKey { get; }

		// Token: 0x060018E1 RID: 6369
		string GetSpecialElementKey(int index);

		// Token: 0x1700060D RID: 1549
		// (get) Token: 0x060018E2 RID: 6370
		bool isNonLocalizedPositiveNameAutoGenerated { get; }

		// Token: 0x1700060E RID: 1550
		// (get) Token: 0x060018E3 RID: 6371
		bool isNonLocalizedNegativeNameAutoGenerated { get; }

		// Token: 0x1700060F RID: 1551
		// (get) Token: 0x060018E4 RID: 6372
		bool isPositiveKeyAutoGenerated { get; }

		// Token: 0x17000610 RID: 1552
		// (get) Token: 0x060018E5 RID: 6373
		bool isNegativeKeyAutoGenerated { get; }

		// Token: 0x17000611 RID: 1553
		// (get) Token: 0x060018E6 RID: 6374
		DeviceLocalizationInfo deviceLocalizationInfo { get; }

		// Token: 0x17000612 RID: 1554
		// (get) Token: 0x060018E7 RID: 6375
		object elementType { get; }

		// Token: 0x17000613 RID: 1555
		// (get) Token: 0x060018E8 RID: 6376
		bool useEditorElementTypeOverride { get; }

		// Token: 0x17000614 RID: 1556
		// (get) Token: 0x060018E9 RID: 6377
		ControllerElementType editorElementTypeOverride { get; }
	}
}
