using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	// Token: 0x02000149 RID: 329
	[Serializable]
	public abstract class InputCategory : lcAibZuWMerLyEDicYNSneVLTvsj
	{
		// Token: 0x17000405 RID: 1029
		// (get) Token: 0x06000E31 RID: 3633
		internal abstract string keyCategory { get; }

		// Token: 0x17000406 RID: 1030
		// (get) Token: 0x06000E32 RID: 3634 RVA: 0x0000D27E File Offset: 0x0000B47E
		// (set) Token: 0x06000E33 RID: 3635 RVA: 0x0000D286 File Offset: 0x0000B486
		public string name
		{
			get
			{
				return this._name;
			}
			internal set
			{
				this._name = value;
			}
		}

		// Token: 0x17000407 RID: 1031
		// (get) Token: 0x06000E34 RID: 3636 RVA: 0x0000D28F File Offset: 0x0000B48F
		// (set) Token: 0x06000E35 RID: 3637 RVA: 0x0000D2B9 File Offset: 0x0000B4B9
		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || this.xIXgFdChYecjrtSQaSxRRmxJoXXm == null)
				{
					return this._descriptiveName;
				}
				return this.xIXgFdChYecjrtSQaSxRRmxJoXXm.QGZglKMnBTLJKJKOPknbgTZKPbAO;
			}
			internal set
			{
				this.nonLocalizedDescriptiveName = value;
			}
		}

		// Token: 0x17000408 RID: 1032
		// (get) Token: 0x06000E36 RID: 3638 RVA: 0x0000D2C2 File Offset: 0x0000B4C2
		// (set) Token: 0x06000E37 RID: 3639 RVA: 0x0000D2CA File Offset: 0x0000B4CA
		public string tag
		{
			get
			{
				return this._tag;
			}
			internal set
			{
				this._tag = value;
			}
		}

		// Token: 0x17000409 RID: 1033
		// (get) Token: 0x06000E38 RID: 3640 RVA: 0x0000D2D3 File Offset: 0x0000B4D3
		// (set) Token: 0x06000E39 RID: 3641 RVA: 0x0000D2DB File Offset: 0x0000B4DB
		public int id
		{
			get
			{
				return this._id;
			}
			internal set
			{
				this._id = value;
			}
		}

		// Token: 0x1700040A RID: 1034
		// (get) Token: 0x06000E3A RID: 3642 RVA: 0x0000D2E4 File Offset: 0x0000B4E4
		// (set) Token: 0x06000E3B RID: 3643 RVA: 0x0000D2EC File Offset: 0x0000B4EC
		public bool userAssignable
		{
			get
			{
				return this._userAssignable;
			}
			internal set
			{
				this._userAssignable = value;
			}
		}

		// Token: 0x1700040B RID: 1035
		// (get) Token: 0x06000E3C RID: 3644 RVA: 0x0000D2F5 File Offset: 0x0000B4F5
		// (set) Token: 0x06000E3D RID: 3645 RVA: 0x0000D2FD File Offset: 0x0000B4FD
		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return this._key;
			}
			set
			{
				this._key = value;
				if (!ReInput.isReady || this.xIXgFdChYecjrtSQaSxRRmxJoXXm == null)
				{
					return;
				}
				this.xIXgFdChYecjrtSQaSxRRmxJoXXm.humgPpaprOCTJdMoIVXMnKxZPobtb();
			}
		}

		// Token: 0x1700040C RID: 1036
		// (get) Token: 0x06000E3E RID: 3646 RVA: 0x0000D321 File Offset: 0x0000B521
		// (set) Token: 0x06000E3F RID: 3647 RVA: 0x0000D329 File Offset: 0x0000B529
		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return this._descriptiveName;
			}
			set
			{
				this._descriptiveName = value;
				if (!ReInput.isReady || this.xIXgFdChYecjrtSQaSxRRmxJoXXm == null)
				{
					return;
				}
				this.xIXgFdChYecjrtSQaSxRRmxJoXXm.OlcAFIbuEHvUomQdyRvLXKoljCWJ();
			}
		}

		// Token: 0x1700040D RID: 1037
		// (get) Token: 0x06000E40 RID: 3648 RVA: 0x0000D34D File Offset: 0x0000B54D
		string lcAibZuWMerLyEDicYNSneVLTvsj.keyCategory
		{
			get
			{
				return this.keyCategory;
			}
		}

		// Token: 0x1700040E RID: 1038
		// (get) Token: 0x06000E41 RID: 3649 RVA: 0x0000D27E File Offset: 0x0000B47E
		string lcAibZuWMerLyEDicYNSneVLTvsj.scriptingName
		{
			get
			{
				return this._name;
			}
		}

		// Token: 0x1700040F RID: 1039
		// (get) Token: 0x06000E42 RID: 3650 RVA: 0x0000D321 File Offset: 0x0000B521
		// (set) Token: 0x06000E43 RID: 3651 RVA: 0x0000D355 File Offset: 0x0000B555
		string lcAibZuWMerLyEDicYNSneVLTvsj.nonLocalizedDescriptiveName
		{
			get
			{
				return this._descriptiveName;
			}
			set
			{
				this._descriptiveName = value;
			}
		}

		// Token: 0x17000410 RID: 1040
		// (get) Token: 0x06000E44 RID: 3652 RVA: 0x0000D2F5 File Offset: 0x0000B4F5
		string lcAibZuWMerLyEDicYNSneVLTvsj.key
		{
			get
			{
				return this._key;
			}
		}

		// Token: 0x17000411 RID: 1041
		// (get) Token: 0x06000E45 RID: 3653 RVA: 0x0000D35E File Offset: 0x0000B55E
		// (set) Token: 0x06000E46 RID: 3654 RVA: 0x0000D366 File Offset: 0x0000B566
		int lcAibZuWMerLyEDicYNSneVLTvsj.autoGeneratedValueFlags
		{
			get
			{
				return this.puAWPYOfCdWcfwWfiyChPcTHbiLB;
			}
			set
			{
				this.puAWPYOfCdWcfwWfiyChPcTHbiLB = value;
			}
		}

		// Token: 0x06000E47 RID: 3655 RVA: 0x000033F4 File Offset: 0x000015F4
		public InputCategory()
		{
		}

		// Token: 0x06000E48 RID: 3656 RVA: 0x00052E68 File Offset: 0x00051068
		public InputCategory(InputCategory A_1)
		{
			this._name = A_1._name;
			this._descriptiveName = A_1._descriptiveName;
			this._key = A_1._key;
			this._tag = A_1._tag;
			this._id = A_1._id;
			this._userAssignable = A_1._userAssignable;
			this.puAWPYOfCdWcfwWfiyChPcTHbiLB = A_1.puAWPYOfCdWcfwWfiyChPcTHbiLB;
		}

		// Token: 0x06000E49 RID: 3657 RVA: 0x0000D36F File Offset: 0x0000B56F
		internal virtual void AdhUFRQHbIPQhLkhPNdOptnZYpLD()
		{
			this.xIXgFdChYecjrtSQaSxRRmxJoXXm = wAaCrzUbQDdcHiRBVWRRKbzVqQGMA.IiaGHlgKOVmnRRwgItCgkNsRcnrF(this);
		}

		// Token: 0x06000E4A RID: 3658 RVA: 0x00002FF9 File Offset: 0x000011F9
		internal virtual void kfObqanLScTcVFWnrgBWhuUanFgD()
		{
		}

		// Token: 0x040008CB RID: 2251
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _name;

		// Token: 0x040008CC RID: 2252
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _descriptiveName;

		// Token: 0x040008CD RID: 2253
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _key;

		// Token: 0x040008CE RID: 2254
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		// Token: 0x040008CF RID: 2255
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected int _id;

		// Token: 0x040008D0 RID: 2256
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected bool _userAssignable;

		// Token: 0x040008D1 RID: 2257
		[NonSerialized]
		private wAaCrzUbQDdcHiRBVWRRKbzVqQGMA xIXgFdChYecjrtSQaSxRRmxJoXXm;

		// Token: 0x040008D2 RID: 2258
		[NonSerialized]
		private int puAWPYOfCdWcfwWfiyChPcTHbiLB;
	}
}
