using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	// Token: 0x0200014C RID: 332
	[Serializable]
	public sealed class InputLayout : lcAibZuWMerLyEDicYNSneVLTvsj
	{
		// Token: 0x17000417 RID: 1047
		// (get) Token: 0x06000E57 RID: 3671 RVA: 0x0000D41F File Offset: 0x0000B61F
		// (set) Token: 0x06000E58 RID: 3672 RVA: 0x0000D427 File Offset: 0x0000B627
		public string name
		{
			get
			{
				return this._name;
			}
			internal set
			{
				this._name = value;
			}
		}

		// Token: 0x17000418 RID: 1048
		// (get) Token: 0x06000E59 RID: 3673 RVA: 0x0000D430 File Offset: 0x0000B630
		// (set) Token: 0x06000E5A RID: 3674 RVA: 0x0000D45A File Offset: 0x0000B65A
		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || this.pLNfBjDeFwMzOyJBTsNpoRnhPhne == null)
				{
					return this._descriptiveName;
				}
				return this.pLNfBjDeFwMzOyJBTsNpoRnhPhne.QGZglKMnBTLJKJKOPknbgTZKPbAO;
			}
			internal set
			{
				this.nonLocalizedDescriptiveName = value;
			}
		}

		// Token: 0x17000419 RID: 1049
		// (get) Token: 0x06000E5B RID: 3675 RVA: 0x0000D463 File Offset: 0x0000B663
		// (set) Token: 0x06000E5C RID: 3676 RVA: 0x0000D46B File Offset: 0x0000B66B
		public int id
		{
			get
			{
				return this._id;
			}
			internal set
			{
				this._id = value;
			}
		}

		// Token: 0x1700041A RID: 1050
		// (get) Token: 0x06000E5D RID: 3677 RVA: 0x0000D474 File Offset: 0x0000B674
		// (set) Token: 0x06000E5E RID: 3678 RVA: 0x0000D47C File Offset: 0x0000B67C
		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return this._key;
			}
			set
			{
				this._key = value;
				if (!ReInput.isReady || this.pLNfBjDeFwMzOyJBTsNpoRnhPhne == null)
				{
					return;
				}
				this.pLNfBjDeFwMzOyJBTsNpoRnhPhne.humgPpaprOCTJdMoIVXMnKxZPobtb();
			}
		}

		// Token: 0x1700041B RID: 1051
		// (get) Token: 0x06000E5F RID: 3679 RVA: 0x0000D4A0 File Offset: 0x0000B6A0
		// (set) Token: 0x06000E60 RID: 3680 RVA: 0x0000D4A8 File Offset: 0x0000B6A8
		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return this._descriptiveName;
			}
			set
			{
				this._descriptiveName = value;
				if (!ReInput.isReady || this.pLNfBjDeFwMzOyJBTsNpoRnhPhne == null)
				{
					return;
				}
				this.pLNfBjDeFwMzOyJBTsNpoRnhPhne.OlcAFIbuEHvUomQdyRvLXKoljCWJ();
			}
		}

		// Token: 0x1700041C RID: 1052
		// (get) Token: 0x06000E61 RID: 3681 RVA: 0x0000D4CC File Offset: 0x0000B6CC
		string lcAibZuWMerLyEDicYNSneVLTvsj.keyCategory
		{
			get
			{
				return "controller_map/layout";
			}
		}

		// Token: 0x1700041D RID: 1053
		// (get) Token: 0x06000E62 RID: 3682 RVA: 0x0000D41F File Offset: 0x0000B61F
		string lcAibZuWMerLyEDicYNSneVLTvsj.scriptingName
		{
			get
			{
				return this._name;
			}
		}

		// Token: 0x1700041E RID: 1054
		// (get) Token: 0x06000E63 RID: 3683 RVA: 0x0000D4A0 File Offset: 0x0000B6A0
		// (set) Token: 0x06000E64 RID: 3684 RVA: 0x0000D4D3 File Offset: 0x0000B6D3
		string lcAibZuWMerLyEDicYNSneVLTvsj.nonLocalizedDescriptiveName
		{
			get
			{
				return this._descriptiveName;
			}
			set
			{
				this._descriptiveName = value;
			}
		}

		// Token: 0x1700041F RID: 1055
		// (get) Token: 0x06000E65 RID: 3685 RVA: 0x0000D474 File Offset: 0x0000B674
		string lcAibZuWMerLyEDicYNSneVLTvsj.key
		{
			get
			{
				return this._key;
			}
		}

		// Token: 0x17000420 RID: 1056
		// (get) Token: 0x06000E66 RID: 3686 RVA: 0x0000D4DC File Offset: 0x0000B6DC
		// (set) Token: 0x06000E67 RID: 3687 RVA: 0x0000D4E4 File Offset: 0x0000B6E4
		int lcAibZuWMerLyEDicYNSneVLTvsj.autoGeneratedValueFlags
		{
			get
			{
				return this.OPOPiaPRVwplfjBTUXWzCbkPXBpV;
			}
			set
			{
				this.OPOPiaPRVwplfjBTUXWzCbkPXBpV = value;
			}
		}

		// Token: 0x06000E68 RID: 3688 RVA: 0x000033F4 File Offset: 0x000015F4
		public InputLayout()
		{
		}

		// Token: 0x06000E69 RID: 3689 RVA: 0x00052ED0 File Offset: 0x000510D0
		public InputLayout(InputLayout A_1) : this()
		{
			this._name = A_1._name;
			this._descriptiveName = A_1._descriptiveName;
			this._key = A_1._key;
			this._id = A_1._id;
			this.OPOPiaPRVwplfjBTUXWzCbkPXBpV = A_1.OPOPiaPRVwplfjBTUXWzCbkPXBpV;
		}

		// Token: 0x06000E6A RID: 3690 RVA: 0x0000D4ED File Offset: 0x0000B6ED
		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		// Token: 0x06000E6B RID: 3691 RVA: 0x0000D4F5 File Offset: 0x0000B6F5
		internal void umDdRyEUMxfHzRybWFTiBUrgIhMvB()
		{
			this.pLNfBjDeFwMzOyJBTsNpoRnhPhne = wAaCrzUbQDdcHiRBVWRRKbzVqQGMA.IiaGHlgKOVmnRRwgItCgkNsRcnrF(this);
		}

		// Token: 0x06000E6C RID: 3692 RVA: 0x00002FF9 File Offset: 0x000011F9
		internal void vFAvmtHesVLYKEQxupRqwXUSdzUU()
		{
		}

		// Token: 0x040008D6 RID: 2262
		private const string keyCategory = "controller_map/layout";

		// Token: 0x040008D7 RID: 2263
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		// Token: 0x040008D8 RID: 2264
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		// Token: 0x040008D9 RID: 2265
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		// Token: 0x040008DA RID: 2266
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		// Token: 0x040008DB RID: 2267
		[NonSerialized]
		private wAaCrzUbQDdcHiRBVWRRKbzVqQGMA pLNfBjDeFwMzOyJBTsNpoRnhPhne;

		// Token: 0x040008DC RID: 2268
		[NonSerialized]
		private int OPOPiaPRVwplfjBTUXWzCbkPXBpV;
	}
}
