using System;
using Rewired;

// Token: 0x02000436 RID: 1078
[CustomClassObfuscation(renamePubIntMembers = false, renamePrivateMembers = false)]
internal interface lcAibZuWMerLyEDicYNSneVLTvsj
{
	// Token: 0x17000A46 RID: 2630
	// (get) Token: 0x06002B6F RID: 11119
	string keyCategory { get; }

	// Token: 0x17000A47 RID: 2631
	// (get) Token: 0x06002B70 RID: 11120
	string scriptingName { get; }

	// Token: 0x17000A48 RID: 2632
	// (get) Token: 0x06002B71 RID: 11121
	// (set) Token: 0x06002B72 RID: 11122
	string nonLocalizedDescriptiveName { get; set; }

	// Token: 0x17000A49 RID: 2633
	// (get) Token: 0x06002B73 RID: 11123
	string key { get; }

	// Token: 0x17000A4A RID: 2634
	// (get) Token: 0x06002B74 RID: 11124
	// (set) Token: 0x06002B75 RID: 11125
	int autoGeneratedValueFlags { get; set; }
}
