using System;
using Rewired;

// Token: 0x0200045A RID: 1114
[CustomClassObfuscation(renamePubIntMembers = false, renamePrivateMembers = false)]
internal interface VHSvqsZIGaGVcFIeminrliAGzvFf
{
	// Token: 0x17000A83 RID: 2691
	// (get) Token: 0x06002C75 RID: 11381
	string keyCategory { get; }

	// Token: 0x17000A84 RID: 2692
	// (get) Token: 0x06002C76 RID: 11382
	string key { get; }

	// Token: 0x17000A85 RID: 2693
	// (get) Token: 0x06002C77 RID: 11383
	// (set) Token: 0x06002C78 RID: 11384
	int autoGeneratedValueFlags { get; set; }
}
