using System;

// Token: 0x0200046B RID: 1131
internal class yihTpXwYRQeSgwOEbtSzbnrtVtcx : VHSvqsZIGaGVcFIeminrliAGzvFf
{
	// Token: 0x17000AAD RID: 2733
	// (get) Token: 0x06002D13 RID: 11539 RVA: 0x00022AA3 File Offset: 0x00020CA3
	public ozwyApMBmHahgljmPNfDTvQyQcEL BofiMWIluiqJmiudNEhAzLbqpQd
	{
		get
		{
			return this.hiYjOXesNONvWKCOVAvoFxHvDlXm;
		}
	}

	// Token: 0x06002D14 RID: 11540 RVA: 0x00022AAB File Offset: 0x00020CAB
	public yihTpXwYRQeSgwOEbtSzbnrtVtcx(ozwyApMBmHahgljmPNfDTvQyQcEL A_1, string A_2, string A_3)
	{
		if (A_1 == null)
		{
			throw new ArgumentNullException();
		}
		this.hiYjOXesNONvWKCOVAvoFxHvDlXm = A_1;
		this.kQkyiUyAzCEQRiapZvFhElqOztpM = A_2;
		this.oFERMcVyyszrZeSdCtpqaMPPXPFd = A_3;
		A_1.IDyLDaZuVIdksxRfLlDpFQVrSiiJ(this);
	}

	// Token: 0x06002D15 RID: 11541 RVA: 0x00022AD8 File Offset: 0x00020CD8
	public virtual bool OsHVrfDSAljTOEUUeQYeDorahure(yihTpXwYRQeSgwOEbtSzbnrtVtcx A_1)
	{
		return A_1 != null && base.GetType() == A_1.GetType() && this.hiYjOXesNONvWKCOVAvoFxHvDlXm.cHdOpXaaqJiUOiddewfaYZgEgMev(A_1.hiYjOXesNONvWKCOVAvoFxHvDlXm);
	}

	// Token: 0x17000AAE RID: 2734
	// (get) Token: 0x06002D16 RID: 11542 RVA: 0x00022B05 File Offset: 0x00020D05
	string VHSvqsZIGaGVcFIeminrliAGzvFf.keyCategory
	{
		get
		{
			return this.kQkyiUyAzCEQRiapZvFhElqOztpM;
		}
	}

	// Token: 0x17000AAF RID: 2735
	// (get) Token: 0x06002D17 RID: 11543 RVA: 0x00022B0D File Offset: 0x00020D0D
	string VHSvqsZIGaGVcFIeminrliAGzvFf.key
	{
		get
		{
			return this.oFERMcVyyszrZeSdCtpqaMPPXPFd;
		}
	}

	// Token: 0x17000AB0 RID: 2736
	// (get) Token: 0x06002D18 RID: 11544 RVA: 0x00022B15 File Offset: 0x00020D15
	// (set) Token: 0x06002D19 RID: 11545 RVA: 0x00022B1D File Offset: 0x00020D1D
	int VHSvqsZIGaGVcFIeminrliAGzvFf.autoGeneratedValueFlags
	{
		get
		{
			return this.sFccFzXiQnYWBRpbADIEXDHMDXACA;
		}
		set
		{
			this.sFccFzXiQnYWBRpbADIEXDHMDXACA = value;
		}
	}

	// Token: 0x17000AB1 RID: 2737
	// (get) Token: 0x06002D1A RID: 11546 RVA: 0x00022B05 File Offset: 0x00020D05
	public string keyCategory
	{
		get
		{
			return this.kQkyiUyAzCEQRiapZvFhElqOztpM;
		}
	}

	// Token: 0x17000AB2 RID: 2738
	// (get) Token: 0x06002D1B RID: 11547 RVA: 0x00022B0D File Offset: 0x00020D0D
	public string key
	{
		get
		{
			return this.oFERMcVyyszrZeSdCtpqaMPPXPFd;
		}
	}

	// Token: 0x04001967 RID: 6503
	protected readonly ozwyApMBmHahgljmPNfDTvQyQcEL hiYjOXesNONvWKCOVAvoFxHvDlXm;

	// Token: 0x04001968 RID: 6504
	private readonly string kQkyiUyAzCEQRiapZvFhElqOztpM;

	// Token: 0x04001969 RID: 6505
	private readonly string oFERMcVyyszrZeSdCtpqaMPPXPFd;

	// Token: 0x0400196A RID: 6506
	private int sFccFzXiQnYWBRpbADIEXDHMDXACA;
}
