using System;
using Rewired.Internal.Localization;

// Token: 0x0200044F RID: 1103
internal class ZVPfClanMEpKBFLxIAoHiukFixhQe : lcAibZuWMerLyEDicYNSneVLTvsj
{
	// Token: 0x17000A6A RID: 2666
	// (get) Token: 0x06002C24 RID: 11300 RVA: 0x00021DC5 File Offset: 0x0001FFC5
	public VhrRjYDSXtDmPGPepEmutTeotlnr OkKeiGgkmOgHtplbshWSqKJvCpSw
	{
		get
		{
			return this.nQHfhBewNPmhVMadNrCFfmmVDYPfb;
		}
	}

	// Token: 0x06002C25 RID: 11301 RVA: 0x00021DCD File Offset: 0x0001FFCD
	public ZVPfClanMEpKBFLxIAoHiukFixhQe(VhrRjYDSXtDmPGPepEmutTeotlnr A_1, string A_2, string A_3, string A_4, string A_5)
	{
		if (A_1 == null)
		{
			throw new ArgumentNullException();
		}
		this.nQHfhBewNPmhVMadNrCFfmmVDYPfb = A_1;
		this.SQrKelSfbBocjgNKgcKQUpnIQNOv = A_2;
		this.NXTLbBvVBCaMqiJdjjZMcbQruABD = A_3;
		this.ZgwyJTRzVnuQzhiDvIFoCvpDIlTPA = A_4;
		this.WJOFoUfoVHBLTRAOLtzZbmxqJyslA = A_5;
		A_1.PZWBGaYSuZufYilwbeAEIstyhayX(this);
	}

	// Token: 0x06002C26 RID: 11302 RVA: 0x00021E0A File Offset: 0x0002000A
	public virtual bool VoGiSTExcJgxYQLQIcAYFckJxHxl(ZVPfClanMEpKBFLxIAoHiukFixhQe A_1, bool A_2)
	{
		return A_1 != null && base.GetType() == A_1.GetType() && this.nQHfhBewNPmhVMadNrCFfmmVDYPfb.BlTKThqPfnWgppHXaUsFTRxHgLOL(A_1.nQHfhBewNPmhVMadNrCFfmmVDYPfb, A_2);
	}

	// Token: 0x17000A6B RID: 2667
	// (get) Token: 0x06002C27 RID: 11303 RVA: 0x00021E38 File Offset: 0x00020038
	string lcAibZuWMerLyEDicYNSneVLTvsj.keyCategory
	{
		get
		{
			return this.SQrKelSfbBocjgNKgcKQUpnIQNOv;
		}
	}

	// Token: 0x17000A6C RID: 2668
	// (get) Token: 0x06002C28 RID: 11304 RVA: 0x00021E40 File Offset: 0x00020040
	string lcAibZuWMerLyEDicYNSneVLTvsj.scriptingName
	{
		get
		{
			return this.NXTLbBvVBCaMqiJdjjZMcbQruABD;
		}
	}

	// Token: 0x17000A6D RID: 2669
	// (get) Token: 0x06002C29 RID: 11305 RVA: 0x00021E48 File Offset: 0x00020048
	// (set) Token: 0x06002C2A RID: 11306 RVA: 0x00021E50 File Offset: 0x00020050
	string lcAibZuWMerLyEDicYNSneVLTvsj.nonLocalizedDescriptiveName
	{
		get
		{
			return this.ZgwyJTRzVnuQzhiDvIFoCvpDIlTPA;
		}
		set
		{
			this.ZgwyJTRzVnuQzhiDvIFoCvpDIlTPA = value;
		}
	}

	// Token: 0x17000A6E RID: 2670
	// (get) Token: 0x06002C2B RID: 11307 RVA: 0x00021E59 File Offset: 0x00020059
	string lcAibZuWMerLyEDicYNSneVLTvsj.key
	{
		get
		{
			return this.WJOFoUfoVHBLTRAOLtzZbmxqJyslA;
		}
	}

	// Token: 0x17000A6F RID: 2671
	// (get) Token: 0x06002C2C RID: 11308 RVA: 0x00021E61 File Offset: 0x00020061
	// (set) Token: 0x06002C2D RID: 11309 RVA: 0x00021E69 File Offset: 0x00020069
	int lcAibZuWMerLyEDicYNSneVLTvsj.autoGeneratedValueFlags
	{
		get
		{
			return this.ZUqoHkzOwfaVkrZxjnIdCOUdDDaDA;
		}
		set
		{
			this.ZUqoHkzOwfaVkrZxjnIdCOUdDDaDA = value;
		}
	}

	// Token: 0x17000A70 RID: 2672
	// (get) Token: 0x06002C2E RID: 11310 RVA: 0x00021E38 File Offset: 0x00020038
	public string keyCategory
	{
		get
		{
			return this.SQrKelSfbBocjgNKgcKQUpnIQNOv;
		}
	}

	// Token: 0x17000A71 RID: 2673
	// (get) Token: 0x06002C2F RID: 11311 RVA: 0x00021E40 File Offset: 0x00020040
	public string scriptingName
	{
		get
		{
			return this.NXTLbBvVBCaMqiJdjjZMcbQruABD;
		}
	}

	// Token: 0x17000A72 RID: 2674
	// (get) Token: 0x06002C30 RID: 11312 RVA: 0x00021E72 File Offset: 0x00020072
	public string tzWklwFEyXNboLyCXqlDxIMkksCC
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return this.ZgwyJTRzVnuQzhiDvIFoCvpDIlTPA;
			}
			return this.nQHfhBewNPmhVMadNrCFfmmVDYPfb.QGZglKMnBTLJKJKOPknbgTZKPbAO;
		}
	}

	// Token: 0x17000A73 RID: 2675
	// (get) Token: 0x06002C31 RID: 11313 RVA: 0x00021E48 File Offset: 0x00020048
	public string nonLocalizedDescriptiveName
	{
		get
		{
			return this.ZgwyJTRzVnuQzhiDvIFoCvpDIlTPA;
		}
	}

	// Token: 0x17000A74 RID: 2676
	// (get) Token: 0x06002C32 RID: 11314 RVA: 0x00021E59 File Offset: 0x00020059
	public string key
	{
		get
		{
			return this.WJOFoUfoVHBLTRAOLtzZbmxqJyslA;
		}
	}

	// Token: 0x04001912 RID: 6418
	protected readonly VhrRjYDSXtDmPGPepEmutTeotlnr nQHfhBewNPmhVMadNrCFfmmVDYPfb;

	// Token: 0x04001913 RID: 6419
	private readonly string SQrKelSfbBocjgNKgcKQUpnIQNOv;

	// Token: 0x04001914 RID: 6420
	private readonly string NXTLbBvVBCaMqiJdjjZMcbQruABD;

	// Token: 0x04001915 RID: 6421
	private string ZgwyJTRzVnuQzhiDvIFoCvpDIlTPA;

	// Token: 0x04001916 RID: 6422
	private readonly string WJOFoUfoVHBLTRAOLtzZbmxqJyslA;

	// Token: 0x04001917 RID: 6423
	private int ZUqoHkzOwfaVkrZxjnIdCOUdDDaDA;
}
